name: CICD

on:
    push:
        branches:
           - deploy-on-ec2

jobs:
    build:
        runs-on: ubuntu-latest
        steps: 
            - name: Checkout Source
              uses: actions/checkout@v3
            - name: login to dockerhub
              run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD}}
            - name: Build docker image
              run: docker build -t muskan04yadav/react-redux .
            - name: publish image to docker hub
              run: docker push muskan04yadav/react-redux:latest
    deploy:
        needs: build
        runs-on: aws-ec2
        steps:
            - name: pull image from dockerhub
              run: docker pull muskan04yadav/react-redux:latest
            - name: Delete old containers
              run: docker rm -f reactContainer
            - name: run docker container
              run: docker run -d -p 4100:80 --name reactContainer muskan04yadav/react-redux


